### ISSUE TITLE
[Bug] When Replacing Ultima Weapon with another Ultima Weapon, Blank Placeholder icon displays instead

### ISSUE THREAD

**Issue by thirdslipper** [jedmund/hensei-web#119]
[Description] In a grid with an existing Ultima Weapon (any), when replaced with another Ultima Weapon (any), one is presented with a prompt to confirm the replacement, but once confirmed, the new weapon does not appear until the page is refreshed.

[Reproduction] 
1. Create a weapon grid with a ultima weapon
2. Replace ultima weapon with another ultima weapon 
![image](https://user-images.githubusercontent.com/12239438/210282249-c1466ac7-c468-47ca-88bb-1f5284bae728.png)
3. Existing ultima weapon should be blank
4. Reload the page, the new weapon should show up in the then blank grid slot 

[Notes] one can interact with the blank weapon slot as if the new ultima is in place, replacing will function, but placeholder will override the icon
![image](https://user-images.githubusercontent.com/12239438/210282544-fd1fe9ac-f56a-4649-a05f-a4d4ca531e49.png)

**Comment by jedmund** [comment]
The blank placeholder is an asset issue. I need to manually rename them for weapons that have choosable elements and forgot about the square size.

The underlying bug here is fixed though, so I'm going to close this!

**Comment by jedmund** [comment]
Reopening this because I found hints of this bug again. Right now, it asks you to confirm, and swaps the weapon in the UI, but when you refresh the weapon was not set, and can't be set into the slot.

Steps to repro above should work, I saw with an Opus. Refresh to find bug after replacing.
