### ISSUE TITLE
More robust filters for team parameters and properties

### ISSUE THREAD

**Issue by jedmund** [jedmund/hensei-web#196]
From @Nadya
> Filters to hide Untitled, No Raid, or Anonymous submissions. All the good builds get drowned in Untitled junk submitted by Anonymous (which are probably mostly people sharing a build with their clannies - as a good amount of this junk looks to be Fire GW variants)  but as the site grows the increased amount of nameless junk will be an issue for finding actually useful things. Especially if browsing the week prior or week of GW.

This is a good extension to making `full_auto`, `charge_attack`, etc. filterable entities for teams.

- [ ] Allow filtering by party properties, such as `full_auto`, `charge_attack`, etc.
- [ ] Allow filtering of low-effort teams, such as `Untitled` parties, Anonymous submissions, or teams with no raid set.

**Comment by NadyaNayme** [comment]
If you see this, sorry Nadya, Jed pinged the wrong Nadya. :P
