### ISSUE TITLE
Feature Request: Allow Replicard Sandbox teams to specify Books

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#248]
Could go somewhere in here if you set your raid to a sandbox boss as shown:
![image](https://user-images.githubusercontent.com/1794735/222404319-dd84407b-5853-4318-ba1e-9d7afac9aff6.png)

**Comment by jedmund** [comment]
This is a good request. I will look into implementing this in the next release.

**Comment by jedmund** [comment]
This was added in #316
