### ISSUE TITLE
Sephira weapons can not be included in Additional Weapon slots

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#249]
As seen: 
![image](https://user-images.githubusercontent.com/1794735/222982308-f613f6fe-8901-4b17-9b71-17ccc5038174.png)

**Comment by jedmund** [comment]
oh thats bad

how'd that happen

i'll fix that this weekend

**Comment by jedmund** [comment]
Okay, this is fixed now! Somehow I forgot to set the `extra` flag on those weapons.
