### ISSUE TITLE
No easy option is available for resetting subskills

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#254]
Apologies for the issue spam, I'm just making them as I test out stuff and find them. Anyway, as far as I can tell, there's no obvious way to remove a subskill once it's been set. The only option I've been able to find was to set it to a class-specific one and then change class.

**Comment by jedmund** [comment]
This isn't spam! It's incredibly helpful and motivating to know someone cares enough to go through and report things like this, so thank you very much!

You're right that there is no easy way to clear a skill right now. I will look into adding it in the next update. Technically it's easy, so this is more of a design problem than anything.

**Comment by Vazkii** [comment]
If you're wondering why I'm coming across so many issues, it's not an indicator of the app's quality (in fact, it's fantastic and I have to give you huge props for it), but it's because I'm working on some bookmarklets to quickly move your teams from ingame to the app ([Vazkii/hensei-transfer](https://github.com/Vazkii/hensei-transfer)), so I'm naturally going to butt into all the small things while trying to reverse engineer the api calls.

**Comment by jedmund** [comment]
Oh this is awesome! 

You don't have to reverse engineer the calls! If you join the [granblue-tools Discord](https://discord.gg/tsq5SqSV), I can give you any info you need! Some people there wanted an API documentation too but I just haven't gotten around to it. 

Hopefully you've also seen [hensei-api](https://github.com/jedmund/hensei-api) too?

**Comment by Vazkii** [comment]
Oh I know the api is open, I've seen that, I mean more figuring out which actions in the UI result in which API calls.
