### ISSUE TITLE
Eternal Transcendance popup is shown as 250 instead of 150

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#255]
![image](https://user-images.githubusercontent.com/1794735/225192548-a8510b16-936b-497c-ad7f-3a68cac57de2.png)

**Comment by jedmund** [comment]
Oh weird, I think this is me being a dunce and not associating that number with the object type (Character vs Summon).

Also that star looks like ass, what the hell happened?

I'll get this fixed.
