### ISSUE TITLE
Grand Awakening is not available

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#256]
![image](https://user-images.githubusercontent.com/1794735/225193513-12ff3820-034e-4810-acf5-abc706a2a3c5.png)
![image](https://user-images.githubusercontent.com/1794735/225193526-c4844c19-7572-4826-8057-7c8e1f2a35f1.png)

**Comment by jedmund** [comment]
I started working on this over the weekend. This technically works a little differently than existing awakenings since each individual weapon has different types (like AX Skills) so it is going to take a bit more time to add.

Thank you for adding this issue for visibility!
