### ISSUE TITLE
Bahamut 250 does not change sprite

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#257]
Incredibly minor, but it gets a red glow at 250
![image](https://user-images.githubusercontent.com/1794735/225196218-23fe0624-89cf-4213-97d1-57e76047b60b.png)
![image](https://user-images.githubusercontent.com/1794735/225196290-e35cf596-10e3-42dd-a3c8-38a7dc2610fc.png)

**Comment by jedmund** [comment]
lmao really? i didn't even know, neat

ok i'll fix this at some point

**Comment by jedmund** [comment]
This was fixed (I think when Lucifer was added)
