### ISSUE TITLE
"Auto Guard" text status is tied to Full Auto toggle

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#272]
![image](https://user-images.githubusercontent.com/1794735/225983786-72d9de79-5e10-4013-ba48-53471f50ac07.png)
As seen here, Auto Guard is off but shows on because Full Auto is on. Toggling off Full Auto also causes Auto Guard to show as off.

**Comment by jedmund** [comment]
This is working fine in my dev environment which makes this one step spookier than just "I'm a dumbass"

**Comment by jedmund** [comment]
Looks like I fixed this at some point so closing this issue
