### ISSUE TITLE
Exo Australis has incorrect Awakening options

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#304]
![image](https://github.com/jedmund/hensei-web/assets/1794735/bef6d705-d4cf-4c9a-8259-46a13ee63b81)

It actually only supports Attack and Special. The level ranges are also incorrect, as it can only go up to 10.

**Comment by jedmund** [comment]
This will be updated with the larger Awakening update that includes Primal weapons.

Currently all weapons have the same Awakening types and levels because before the Primal Weapons update, that was true :')
